language: ruby
rvm: 2.2
cache:
  directories:
  - vendor/bundle
bundler_args: --deployment
install: script/install --deploy
script: script/build
branches:
  only:
    - site
env:
  global:
  - secure: aM7WhSShFDNQX2qpIhuWfpJMnaGX5euA9AaBOLuIRamXWkkI1GrZycX/0OLNg8Vfxe8Ei34Q4ge78Lm/Ty8RaZeIDyvTA45pTcHtCC7KUkh8Jq1lH2yE6jn7E3Xwje7VeEuSruupsq1K2W5tma51oo1SZZyU2sfFJaKYgfTb5pFGvua9xWntutsmvmG+GPCEc+Xl5Pi5h8Q56VAX6KQJ6DYXMHICJpF75FnMQ3pYq+n9KtIdOBa6/8QAoMg136YDu7BQhE+2ALnJ0hMvIAl17enzaDro+FhYg73hw1PdmM1XK4Td5UFsvrjMJFU1Bi4b5g/EfG9xqlwCxeCmrKGF5uzelCTKdvpooPpJRPrhTDZ7yZRkLpfODbfEsWS8wvB/QPnrWRP2G/rYl0QGzsb6RG5WDMkBLJz5K2w4jLsX1GziN9BJdsizM5Bt/Vv9VDSI4bxDQoxWm9J9a+XBfaVI1hYV1CXtGsayqDszkUqGzorwbAUFLxdg4gXrrvHocnnm5Hsv6LPy5ptlcgjqbDwBB5UCS0jbKre/cLlngzmI9lBstaANqmMbUqPH5NiHJJyWn4i4CFNbXSTQBJw6Yo0j4Y87YTI9879gf+YxtYo7eABGbDIfWHBwZoeGQEDJ8O9iosKwevVNhXRCGrUZt6gMshjTbE5GIyXc5mv3qFPPVuo=
  - PAGES_REPO_NWO=$TRAVIS_REPO_SLUG JEKYLL_GITHUB_TOKEN=$GH_TOKEN
